version: '3'

volumes:
  meus-restaurantes-data-57:
    driver: local

services:

  mysql-database-57:
    image: mysql:5.7
    volumes:
      - meus-restaurantes-data-57:/var/lib/mysql:delegated
    command: mysqld --show-compatibility-56=ON --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo

  meus-restaurantes:
    build: .
    ports:
      - 8080:80
    volumes:
      - .:/app
    links:
      - mysql-database-57